"""Añadir apellido a usuarios

Revision ID: 19c0025b104f
Revises: a8e120ddbf33
Create Date: 2026-07-02 10:32:19.533983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c0025b104f'
down_revision: Union[str, Sequence[str], None] = 'a8e120ddbf33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('apellido', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'apellido')
    # ### end Alembic commands ###
